name: Update CS Prices

on:
    schedule:
        - cron: "0 12 * * *"

    workflow_dispatch:

jobs:
    download:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v3
            - name: Update prices
              run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
            - name: Get current date and time
              id: current_datetime
              run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
            - name: Commit & push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Updated CS Prices on ${{ env.CURRENT_DATETIME }}"
